name: Deploy MidnightCodex Theme

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check Theme Structure
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Verify required files
        run: |
          echo "📋 Checking theme structure..."
          test -f package.json && echo "✅ package.json found" || exit 1
          test -f index.hbs && echo "✅ index.hbs found" || exit 1
          test -f post.hbs && echo "✅ post.hbs found" || exit 1
          echo "✅ Theme structure looks good!"

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/hasan/ghost-blog/content/themes
            rm -rf midnightcodex
            git clone git@github.com:HasanHozgur/ghost-theme-midnightcodex.git midnightcodex
            cd /home/hasan
            docker compose -f ghost-blog/docker-compose.yml restart
            echo "✅ MidnightCodex theme deployed successfully!"
