name: Deploy MidnightCodex Theme

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Theme Validation & Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install GScan
        run: npm install -g gscan
      
      - name: Run GScan validation
        run: |
          echo "🔍 Running Ghost theme validation..."
          gscan . --verbose
      
      - name: Verify required files
        run: |
          echo "📋 Checking theme structure..."
          test -f package.json && echo "✅ package.json found" || exit 1
          test -f default.hbs && echo "✅ default.hbs found" || exit 1
          test -f index.hbs && echo "✅ index.hbs found" || exit 1
          test -f post.hbs && echo "✅ post.hbs found" || exit 1
          echo "✅ Theme structure looks good!"

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/hasanhuseyinozgur.dev/content/themes
            rm -rf midnightcodex
            git clone https://github.com/HasanHozgur/ghost-theme-midnightcodex.git midnightcodex
            docker restart ghost-blog
            echo "✅ MidnightCodex theme deployed successfully!"